INSERT INTO db_ricette.recipes(id, number_portion, time_prep, ingredient, title, url_foto)VALUES(1, 4, 30, 'Pasta, Pomodoro, Basilico, Olio', 'Pasta al Pomodoro', 'http://example.com/pasta.jpg');
INSERT INTO db_ricette.recipes(id, number_portion, time_prep, ingredient, title, url_foto )VALUES(2, 2, 15, 'Insalata, Pomodoro, Mozzarella, Basilico', 'Insalata Caprese', 'http://example.com/insalata.jpg');
INSERT INTO db_ricette.recipes(id, number_portion, time_prep, ingredient, title, url_foto)VALUES(3, 4, 40, 'Pollo, Curry, Latte di Cocco, Pepe', 'Pollo al Curry', 'http://example.com/curry.jpg');
INSERT INTO db_ricette.categories(id, name)VALUES(1, 'primo');
INSERT INTO db_ricette.categories(id, name)VALUES(2, 'secondo');
INSERT INTO db_ricette.categories(id, name)VALUES(3, 'contorno');
INSERT INTO db_ricette.categories(id, name)VALUES(4, 'antipasto');
INSERT INTO db_ricette.categories(id, name)VALUES(5, 'dessert');